export const LANGUAGES = [
  { code: "en", label: "English", native: "English" },
  { code: "hi", label: "Hindi", native: "हिन्दी" },
  { code: "mr", label: "Marathi", native: "मराठी" },
  { code: "ta", label: "Tamil", native: "தமிழ்" },
  { code: "te", label: "Telugu", native: "తెలుగు" },
  { code: "bn", label: "Bengali", native: "বাংলা" },
  { code: "gu", label: "Gujarati", native: "ગુજરાતી" },
  { code: "kn", label: "Kannada", native: "ಕನ್ನಡ" },
  { code: "ml", label: "Malayalam", native: "മലയാളം" },
  { code: "pa", label: "Punjabi", native: "ਪੰਜਾਬੀ" },
];

export const STATES_WITH_CITIES = {
  "Andhra Pradesh": ["Visakhapatnam", "Vijayawada", "Guntur", "Nellore", "Kurnool"],
  "Arunachal Pradesh": ["Itanagar", "Naharlagun", "Pasighat"],
  Assam: ["Guwahati", "Silchar", "Dibrugarh", "Jorhat", "Nagaon"],
  Bihar: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur", "Purnia"],
  Chhattisgarh: ["Raipur", "Bhilai", "Bilaspur", "Korba", "Durg"],
  Goa: ["Panaji", "Margao", "Vasco da Gama", "Mapusa"],
  Gujarat: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhavnagar", "Gandhinagar"],
  Haryana: ["Faridabad", "Gurgaon", "Panipat", "Ambala", "Yamunanagar", "Rohtak"],
  "Himachal Pradesh": ["Shimla", "Mandi", "Dharamshala", "Solan"],
  Jharkhand: ["Ranchi", "Jamshedpur", "Dhanbad", "Bokaro", "Deoghar"],
  Karnataka: ["Bengaluru", "Mysuru", "Hubballi", "Mangaluru", "Belagavi", "Kalaburagi"],
  Kerala: ["Thiruvananthapuram", "Kochi", "Kozhikode", "Thrissur", "Kollam"],
  "Madhya Pradesh": ["Bhopal", "Indore", "Jabalpur", "Gwalior", "Ujjain"],
  Maharashtra: [
    "Mumbai", "Pune", "Nagpur", "Thane", "Nashik", "Aurangabad",
    "Solapur", "Kolhapur", "Navi Mumbai", "Vasai-Virar",
  ],
  Manipur: ["Imphal", "Thoubal", "Bishnupur"],
  Meghalaya: ["Shillong", "Tura", "Nongstoin"],
  Mizoram: ["Aizawl", "Lunglei", "Saiha"],
  Nagaland: ["Kohima", "Dimapur", "Mokokchung"],
  Odisha: ["Bhubaneswar", "Cuttack", "Rourkela", "Sambalpur", "Berhampur"],
  Punjab: ["Ludhiana", "Amritsar", "Jalandhar", "Patiala", "Bathinda"],
  Rajasthan: ["Jaipur", "Jodhpur", "Kota", "Bikaner", "Ajmer", "Udaipur"],
  Sikkim: ["Gangtok", "Namchi", "Gyalshing"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli", "Salem", "Tirunelveli"],
  Telangana: ["Hyderabad", "Warangal", "Nizamabad", "Khammam", "Karimnagar"],
  Tripura: ["Agartala", "Udaipur", "Dharmanagar"],
  "Uttar Pradesh": [
    "Lucknow", "Kanpur", "Ghaziabad", "Agra", "Varanasi",
    "Meerut", "Noida", "Allahabad", "Bareilly", "Aligarh",
  ],
  Uttarakhand: ["Dehradun", "Haridwar", "Roorkee", "Haldwani", "Rudrapur"],
  "West Bengal": ["Kolkata", "Asansol", "Siliguri", "Durgapur", "Bardhaman"],
  // Union Territories
  "Andaman and Nicobar Islands": ["Port Blair"],
  Chandigarh: ["Chandigarh"],
  "Dadra and Nagar Haveli and Daman and Diu": ["Daman", "Diu", "Silvassa"],
  Delhi: ["New Delhi", "North Delhi", "South Delhi", "East Delhi", "West Delhi", "Dwarka", "Rohini"],
  "Jammu and Kashmir": ["Srinagar", "Jammu", "Anantnag", "Baramulla"],
  Ladakh: ["Leh", "Kargil"],
  Lakshadweep: ["Kavaratti"],
  Puducherry: ["Puducherry", "Karaikal", "Mahe"],
};

export const STATES = Object.keys(STATES_WITH_CITIES).sort();

export const UI_STRINGS = {
  en: {
    appName: "VoteFlow",
    tagline: "Know Your Vote. Own Your Voice.",
    selectLanguage: "Select Your Language",
    continue: "Continue",
    back: "Back",
    checkEligibility: "Check Eligibility",
    step: "Step",
    of: "of",
    ageLabel: "What is your age?",
    agePlaceholder: "Enter your age",
    stateLabel: "Which state do you live in?",
    statePlaceholder: "Select State",
    cityLabel: "Which city / district?",
    cityPlaceholder: "Select City",
    voterIdLabel: "Do you have a Voter ID card?",
    voterIdYes: "Yes, I have one",
    voterIdNo: "No, I don't",
    voterIdNotSure: "Not sure",
    movedLabel: "Have you recently moved to a new address?",
    movedYes: "Yes, recently moved",
    movedNo: "No, same address",
    result: "Your Eligibility Result",
    nextActions: "Next Steps",
    requiredDocs: "Documents Required",
    boothDetails: "Your Polling Booth",
    openMaps: "Open in Google Maps",
    checkOnECI: "Check on ECI Website",
    lowConfidenceWarning:
      "Booth data is currently unavailable for your area. Please verify on the official ECI portal.",
    source: "Source",
    lastUpdated: "Last updated",
    checking: "Checking your eligibility…",
    loadingBooth: "Fetching booth details…",
  },
  hi: {
    appName: "वोटफ्लो",
    tagline: "अपना वोट जानें। अपनी आवाज़ उठाएं।",
    selectLanguage: "अपनी भाषा चुनें",
    continue: "जारी रखें",
    back: "वापस",
    checkEligibility: "पात्रता जाँचें",
    step: "चरण",
    of: "का",
    ageLabel: "आपकी आयु क्या है?",
    agePlaceholder: "आयु दर्ज करें",
    stateLabel: "आप किस राज्य में रहते हैं?",
    statePlaceholder: "राज्य चुनें",
    cityLabel: "कौन सा शहर / जिला?",
    cityPlaceholder: "शहर चुनें",
    voterIdLabel: "क्या आपके पास मतदाता पहचान पत्र है?",
    voterIdYes: "हाँ, है",
    voterIdNo: "नहीं, नहीं है",
    voterIdNotSure: "निश्चित नहीं",
    movedLabel: "क्या आप हाल ही में नए पते पर आए हैं?",
    movedYes: "हाँ, हाल ही में आया/आई",
    movedNo: "नहीं, वही पता है",
    result: "आपकी पात्रता परिणाम",
    nextActions: "अगले कदम",
    requiredDocs: "आवश्यक दस्तावेज़",
    boothDetails: "आपका मतदान केंद्र",
    openMaps: "गूगल मैप्स में खोलें",
    checkOnECI: "ECI वेबसाइट पर जाँचें",
    lowConfidenceWarning:
      "आपके क्षेत्र के लिए बूथ डेटा उपलब्ध नहीं है। कृपया ECI पोर्टल पर जाँचें।",
    source: "स्रोत",
    lastUpdated: "अंतिम अपडेट",
    checking: "पात्रता जाँच रहे हैं…",
    loadingBooth: "बूथ विवरण प्राप्त कर रहे हैं…",
  },
};

// Fallback English for any language not translated yet
export function getStrings(lang) {
  return UI_STRINGS[lang] || UI_STRINGS.en;
}
